# Generated by Django 2.0.4 on 2018-04-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('time', models.CharField(choices=[('morning', '上午'), ('afternoon', '下午'), ('night', '晚上')], default='morning', max_length=100)),
                ('class_num', models.CharField(default=0, max_length=10, verbose_name='教室')),
                ('order', models.CharField(default=0, max_length=100, verbose_name='预约')),
            ],
            options={
                'verbose_name': '活动信息',
                'verbose_name_plural': '活动信息',
            },
        ),
    ]
